# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 135e133803ccc1ab24b59bfe15171cf2cbea4528207515d3dae22fc884ecae7b3a378c3bc8a8e2e8abf4f188553f23837a8b2a28751c2cf5adb883f32c929bb3

test:
  secret_key_base: 2f189ced545b15b933ce5a6f9f5517c6d0d4ff291f46eb37bc8bb55aa181e3dbe4e2fd1e2ea6df7da65d44511ad1665ef2e60830a632969d80b19dca4e01c46f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
